site_name: Cherry 文档
repo_url: https://github.com/CMHopeSunshine/cherry-orm
repo_name: CMHopeSunshine/cherry-orm
plugins:
  - search:
      separator: '[\s\u200b\-]'
theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
    annotation: material/star-four-points-circle
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    # - navigation.sections
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: red
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: red
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ../src
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - 概述: index.md
  - 安装: install.md
  - 快速开始: quick-start.md
  - 教程:
      - 模型定义: tutorial/definition.md
      - 增删改查:
          - 插入: tutorial/crud/insert.md
          - 更新: tutorial/crud/update.md
          - 删除: tutorial/crud/delete.md
          - 查询: tutorial/crud/query.md
          - 聚合查询: tutorial/crud/aggregation.md
      - 模型关系:
          - 定义: tutorial/relation/difinition.md
          - 查询: tutorial/relation/query.md

extra:
  alternate:
    - name: 简体中文
      link: /
      lang: zh
    - name: English
      link: /en/
      lang: en
